[package]
name = "arcccc-library"
version = "0.0.1"
authors = ["Martin DeMello <martindemello@gmail.com>"]

[lib]
name = "dict_reader"
crate-type = ["staticlib"]

[dependencies]
glib = "^0"
glib-sys = "^0"
libc = "^0"
